# Project runtime configuration parameters.

[paths]
RAW_NPORT = "$DATA_RAW/sec_NPORT"
PROCESSED_NPORT = "$DATA_WORK/sec_NPORT_work"
PROJECT_TEMP = "$DATA_TEMP/heterogeneity_temp"

[general]
random_seed = 42
n_workers = -1
batch_job_verbose = 10
