# Project runtime configuration parameters.

[paths]
RAW_NPORT = "$DATA_RAW/sec_NPORT"
PROCESSED_NPORT = "$DATA_WORK/sec_NPORT_work"
PROJECT_TEMP = "$DATA_TEMP/heterogeneity_temp"

[general]
random_seed = 42
n_workers = -1
batch_job_verbose = 10
SEC_API_KEY="$SEC_API_KEY"

[nport]
process_quarters = { start = "2019q4", end = "2025q2" }
