# Project runtime configuration parameters.

[paths]
RAW_NPORT = "/storage/Dropbox/80_data/raw/sec_NPORT"
PROCESSED_NPORT = "/storage/Dropbox/80_data/work/sec_NPORT_work"
PROJECT_TEMP = "/storage/Dropbox/80_data/temp/heterogeneity_temp"

[general]
random_seed = 42
n_workers = -1
batch_job_verbose = 10